---
# CorfuDB configmaster STREAM-AWARE configuration
#
#
# Required:
# role (string) - org.corfudb.infrastructure.ConfigMasterServer selects the configuration master
# port (number) - the port number to run on
#
# Optional:

role: org.corfudb.infrastructure.ConfigMasterServer
port: 12703
pagesize: 4096
epoch: 0
sequencers:
    - "cdbsts://localhost:12601"
configmasters:
    - "cdbcm://localhost:12703"
layout:
    segments:
        - replication: "cdbnmrp"
          start: 0
          sealed: -1
          layers:
              - nodes:
                  - "nlu://localhost:12701"
              - nodes:
                  - "nlu://localhost:12802"
          replicas: 1
